import React from "react";
import {
  AboutContent,
  AboutIcon,
  AboutImg,
  AboutSecondText,
  AboutSecondTextWrapper,
  AboutSection,
  AboutText,
  AboutTextWrapper,
  AboutTitle,
  AboutTitleDecorate,
} from "./About.styled";
import sprite from "../../img/symbol-defs.svg";
import { aboutImg } from "../../data/images";

const About = () => {
  return (
    <AboutSection id="about">
      <AboutContent className="container">
        <AboutTextWrapper>
          <AboutTitle>
            a Story that started with
            <AboutTitleDecorate>&nbsp;one simple ape</AboutTitleDecorate>
          </AboutTitle>
          <AboutText>
            WHO GOT FED UP WITH BORING AND HYPOCRITIC COMMONPLACE THIS IS HOW
            THE IDEA OF ESCAPING AND DYNAMIC JOURNEY ON THE YACHT
          </AboutText>
        </AboutTextWrapper>
        <AboutSecondTextWrapper>
          <AboutIcon width={24} height={24}>
            <use href={`${sprite}#icon-cross`}></use>
          </AboutIcon>
          <AboutSecondText>
            EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS
            ARE RANDOMLY GENERATED BY USERS
          </AboutSecondText>
        </AboutSecondTextWrapper>
        <picture>
          <source
            srcSet={`${aboutImg.imgDesktop[0]} 1x,${aboutImg.imgDesktop[1]} 2x`}
            media="(min-width: 1280px)"
          />
          <source
            srcSet={`${aboutImg.imgTablet[0]} 1x,${aboutImg.imgTablet[1]} 2x`}
            media="(min-width: 768px)"
          />
          <source
            srcSet={`${aboutImg.imgMobile[0]} 1x,${aboutImg.imgMobile[1]} 2x`}
            media="(max-width: 767px)"
          />
          <AboutImg src={aboutImg.imgMobile[0]} alt="Monkey" />
        </picture>
      </AboutContent>
      <div
        style={{
          width: "100%",
          height: "52px",
          background: "var(--color-brand)",
        }}
      ></div>
    </AboutSection>
  );
};

export default About;
