import React from "react";
import {
  AboutImg,
  AboutSection,
  AboutText,
  AboutTitle,
  AboutTitleDecorate,
} from "./About.styled";
import sprite from "../../img/symbol-defs.svg";
import img from "../../img/about-monkey.png";
import { CrossIcon } from "../../App.styled";

const About = () => {
  return (
    <AboutSection>
      <div className="container">
        <AboutTitle>
          a Story that started with
          <AboutTitleDecorate>&nbsp;one simple ape</AboutTitleDecorate>
        </AboutTitle>
        <AboutText>
          WHO GOT FED UP WITH BORING AND HYPOCRITIC COMMONPLACE THIS IS HOW THE
          IDEA OF ESCAPING AND DYNAMIC JOURNEY ON THE YACHT
        </AboutText>
        <CrossIcon width={24} height={24}>
          <use href={`${sprite}#icon-cross`}></use>
        </CrossIcon>
        <AboutText>
          EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS ARE
          RANDOMLY GENERATED BY USERS
        </AboutText>
        <AboutImg src={img} alt="Monkey" width={216} height={292} />
      </div>
      <div
        style={{
          width: "100%",
          height: "52px",
          background: "var(--color-brand)",
        }}
      ></div>
    </AboutSection>
  );
};

export default About;
